- name: Create net base containers net_{{ vm_set_name }}_{{ item }}
  become: yes
  docker_container:
    name: net_{{ vm_set_name }}_{{ vm_name }}
    image: debian:jessie
    pull: no
    state: started
    restart: no
    tty: yes
    network_mode: none
    detach: True
    capabilities:
      - net_admin
    privileged: yes
    memory: 200M
    memory_swap: 200M
  async: 300
  poll: 0
  loop: "{{ VM_targets|flatten(levels=1) }}"
  loop_control:
    loop_var: vm_name
  register: async_create_results

- name: Wait for creation of net base containers
  become: yes
  async_status:
    jid: "{{ async_create_result_item.ansible_job_id }}"
  loop: "{{ async_create_results.results }}"
  loop_control:
    loop_var: async_create_result_item
  register: async_create_poll_results
  until: async_create_poll_results.finished
  retries: 10
  delay: 30

- name: Create network for ceos container net_{{ vm_set_name }}_{{ vm_name }}
  become: yes
  ceos_network:
    name: net_{{ vm_set_name }}_{{ vm_name }}
    vm_name:    "{{ vm_name }}"
    fp_mtu:     "{{ fp_mtu_size }}"
    max_fp_num: "{{ max_fp_num }}"
    mgmt_bridge: "{{ mgmt_bridge }}"
  loop: "{{ VM_targets|flatten(levels=1) }}"
  loop_control:
    loop_var: vm_name
