- name: Create directory for vm images and vm disks
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "sonic-vm/images"
    - "sonic-vm/disks"

- set_fact:
    src_disk_image: "{{ home_path }}/sonic-vm/images/sonic-vs.img"
    disk_image: "{{ home_path }}/sonic-vm/disks/sonic_{{ dut_name }}.img"
    mgmt_ip_address: " {{ hostvars[dut_name]['ansible_host'] }}"
    serial_port: 9000

- name: Device debug output
  debug: msg="hostname = {{ dut_name }} serial port = {{ serial_port }} ip = {{ mgmt_ip_address }}"

- name: Check destination file existance
  stat: path={{ disk_image }}
  register: file_stat

- name: Copy sonic disk image for {{ dut_name }}
  copy: src={{ src_disk_image }} dest={{ disk_image }} remote_src=True
  when: not file_stat.stat.exists

- name: Define vm {{ dut_name }}
  virt: name={{ dut_name }}
        command=define
        xml="{{ lookup('template', 'templates/sonic.xml.j2') }}"
        uri=qemu:///system
  when: dut_name not in vm_list_defined.list_vms

- name: Start vm {{ dut_name }}
  virt: name={{ dut_name }}
        state=running
        uri=qemu:///system
  when: dut_name not in vm_list_running.list_vms


